import type { TemplateDefinition } from './registry';
import {
  renderBrandLogoReveal,
  renderBrandLogoAnim,
  renderBrandLogoSting,
  renderBrandIntro,
  renderBrandOutro,
  renderBrandWatermark,
  renderBrandLowerThird,
  renderBrandColorTransition,
  renderBrandTitleCard,
  renderBrandEndScreen,
  renderBrandCtaUrl,
} from './brandingGraphics';
import {
  renderCreatorSubscribeCta,
  renderCreatorLikeSub,
  renderCreatorCommentCta,
  renderCreatorVideoIntro,
  renderCreatorChapterTitle,
  renderCreatorComingUp,
  renderCreatorPreviously,
  renderCreatorMeanwhile,
  renderCreatorPov,
  renderCreatorDidYouKnow,
  renderCreatorFactCard,
  renderCreatorTop5,
  renderCreatorCountdown,
  renderCreatorReactionPopup,
  renderCreatorMemePopup,
  renderCreatorEndScreen,
} from './creatorGraphics';
import {
  renderCommProductReveal,
  renderCommProductShowcase,
  renderCommPriceTag,
  renderCommDiscountBadge,
  renderCommSaleAnim,
  renderCommFeatureCallout,
  renderCommProductComparison,
  renderCommProductRotation,
  renderCommBenefitsList,
  renderCommCtaBanner,
  renderCommAppReveal,
  renderCommQrCode,
  renderCommTestimonialCard,
} from './commercialGraphics';
import {
  renderMoneyCoinFlip,
  renderMoneyFallingCoins,
  renderMoneyBanknoteStack,
  renderMoneyRupeeTitle,
  renderMoneyWealthCounter,
  renderMoneyCashExplosion,
  renderMoneyCryptoCoin,
  renderMoneyPiggyBank,
  renderMoneyTransactionPill,
  renderMoneyNetWorth,
  renderMoneyIndianNoteShowcase,
  renderMoneyCashFanning,
  renderMoneyIndianNotesBundle,
} from './moneyGraphics';

// ==========================================
// BRANDING TEMPLATES (11)
// ==========================================
export const BRANDING_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'brand-logo-reveal',
    name: 'Logo Reveal',
    category: 'branding',
    description: 'Geometric energy rings expanding into glowing brand emblem with particle flourish.',
    render: renderBrandLogoReveal,
    defaultConfig: {
      id: 'brand-logo-reveal',
      name: 'Logo Reveal',
      category: 'branding',
      description: 'Dynamic geometric logo reveal with energy rings',
      duration: 3.5,
      fps: 60,
      title: 'MOTIONFORGE',
      subtitle: 'NEXT-GENERATION VIDEO ENGINE',
      brandLogoText: 'M',
      primaryColor: '#6366f1',
      secondaryColor: '#ec4899',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'brand-logo-anim',
    name: 'Logo Animation',
    category: 'branding',
    description: 'Multi-layered rotating gyroscope rings settling into center brand emblem.',
    render: renderBrandLogoAnim,
    defaultConfig: {
      id: 'brand-logo-anim',
      name: 'Logo Animation',
      category: 'branding',
      description: 'Kinetic gyroscope logo animation',
      duration: 3.5,
      fps: 60,
      title: 'STUDIO BRAND',
      subtitle: 'CREATIVE DIRECTION',
      brandLogoText: 'S',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#a855f7',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'brand-logo-sting',
    name: 'Logo Sting',
    category: 'branding',
    description: 'Fast high-impact 2-second bumper sting with flash and sub bass impact.',
    render: renderBrandLogoSting,
    defaultConfig: {
      id: 'brand-logo-sting',
      name: 'Logo Sting',
      category: 'branding',
      description: 'Quick-impact 2-second bumper sting',
      duration: 2.0,
      fps: 60,
      title: 'STING',
      subtitle: 'BUMPER',
      brandLogoText: 'STING',
      primaryColor: '#dc2626',
      secondaryColor: '#ffffff',
      accentColor: '#ffffff',
      textColor: '#ffffff',
      cardColor: '#000000',
      enableSFX: true,
    },
  },
  {
    id: 'brand-intro',
    name: 'Brand Intro',
    category: 'branding',
    description: 'Cinematic agency opener with letterbox bars and luxury typography.',
    render: renderBrandIntro,
    defaultConfig: {
      id: 'brand-intro',
      name: 'Brand Intro',
      category: 'branding',
      description: 'Cinematic agency studio intro with letterbox bars',
      duration: 4.0,
      fps: 60,
      title: 'APEX CREATIVE LABS',
      subtitle: 'PRESENTS A PRODUCTION BY',
      primaryColor: '#f59e0b',
      secondaryColor: '#ffffff',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: '#000000',
      enableSFX: true,
    },
  },
  {
    id: 'brand-outro',
    name: 'Brand Outro',
    category: 'branding',
    description: 'Elegant thank-you outro card with subscription prompt and website link.',
    render: renderBrandOutro,
    defaultConfig: {
      id: 'brand-outro',
      name: 'Brand Outro',
      category: 'branding',
      description: 'End slate with website address and thank-you message',
      duration: 3.5,
      fps: 60,
      title: 'THANK YOU FOR WATCHING',
      subtitle: 'Subscribe for new releases every week',
      websiteUrl: 'WWW.MOTIONFORGE.IO',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'brand-watermark',
    name: 'Animated Watermark',
    category: 'branding',
    description: 'Discreet corner brand bug with animated breathing glow and pill border.',
    render: renderBrandWatermark,
    defaultConfig: {
      id: 'brand-watermark',
      name: 'Animated Watermark',
      category: 'branding',
      description: 'Discreet corner brand watermark with subtle pulse',
      duration: 3.0,
      fps: 60,
      title: 'MOTIONFORGE',
      subtitle: 'PRO',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.82)',
      enableSFX: false,
    },
  },
  {
    id: 'brand-lower-third',
    name: 'Brand Lower Third',
    category: 'branding',
    description: 'Minimalist luxury brand strap with monogram emblem, company name, and status tag.',
    render: renderBrandLowerThird,
    defaultConfig: {
      id: 'brand-lower-third',
      name: 'Brand Lower Third',
      category: 'branding',
      description: 'Luxury brand strap with logo emblem',
      duration: 3.5,
      fps: 60,
      title: 'Brand Organization',
      subtitle: 'Official Partner Network • Verified',
      brandLogoText: 'M',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'brand-color-transition',
    name: 'Brand Colors Transition',
    category: 'branding',
    description: 'Triple angled dynamic color wipe transition overlay using your brand palette.',
    render: renderBrandColorTransition,
    defaultConfig: {
      id: 'brand-color-transition',
      name: 'Brand Colors Transition',
      category: 'branding',
      description: 'Triple-angled brand color transition wipe',
      duration: 1.5,
      fps: 60,
      title: 'TRANSITION',
      subtitle: 'COLOR WIPE',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#ec4899',
      textColor: '#ffffff',
      cardColor: '#000000',
      enableSFX: true,
    },
  },
  {
    id: 'brand-title-card',
    name: 'Branded Title Card',
    category: 'branding',
    description: 'Editorial brand statement card with refined serif typography and accent rule.',
    render: renderBrandTitleCard,
    defaultConfig: {
      id: 'brand-title-card',
      name: 'Branded Title Card',
      category: 'branding',
      description: 'Editorial brand statement card with typography',
      duration: 4.0,
      fps: 60,
      title: 'THE FUTURE OF VISUAL STORYTELLING',
      subtitle: 'Crafted with precision by our worldwide design collective',
      badgeText: 'SPECIAL PRESENTATION',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: '#0a0a0c',
      enableSFX: true,
    },
  },
  {
    id: 'brand-end-screen',
    name: 'Branded End Screen',
    category: 'branding',
    description: 'Dual-video showcase placeholders with center brand avatar and Subscribe circle.',
    render: renderBrandEndScreen,
    defaultConfig: {
      id: 'brand-end-screen',
      name: 'Branded End Screen',
      category: 'branding',
      description: 'Brand end screen with video placeholders',
      duration: 4.0,
      fps: 60,
      title: 'WATCH NEXT',
      subtitle: 'SUBSCRIBE',
      primaryColor: '#dc2626',
      secondaryColor: '#6366f1',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.85)',
      enableSFX: true,
    },
  },
  {
    id: 'brand-cta-url',
    name: 'CTA & Website URL',
    category: 'branding',
    description: 'Sliding pill card with pulsing CTA badge and animated typewriter website URL.',
    render: renderBrandCtaUrl,
    defaultConfig: {
      id: 'brand-cta-url',
      name: 'CTA & Website URL',
      category: 'branding',
      description: 'Sliding pill with button and typing URL simulation',
      duration: 3.5,
      fps: 60,
      title: 'VISIT NOW',
      subtitle: 'WEBSITE',
      ctaText: 'EXPLORE NOW ➔',
      websiteUrl: 'www.motionforge.io/pro',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(11, 15, 25, 0.95)',
      enableSFX: true,
    },
  },
];

// ==========================================
// CREATOR / YOUTUBE TEMPLATES (16)
// ==========================================
export const CREATOR_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'creator-subscribe-cta',
    name: 'Subscribe CTA Banner',
    category: 'creator',
    description: 'Animated subscribe pill with avatar, subscriber counter, and click transition.',
    render: renderCreatorSubscribeCta,
    defaultConfig: {
      id: 'creator-subscribe-cta',
      name: 'Subscribe CTA Banner',
      category: 'creator',
      description: 'Animated Subscribe button with avatar',
      duration: 3.5,
      fps: 60,
      title: 'Creator Studio',
      subtitle: '1.4M Subscribers',
      primaryColor: '#dc2626',
      secondaryColor: '#ffffff',
      accentColor: '#ffffff',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.96)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-like-sub',
    name: '"Like & Subscribe" Pill',
    category: 'creator',
    description: 'Dual-action pill with animated thumbs up like and bell subscribe transformations.',
    render: renderCreatorLikeSub,
    defaultConfig: {
      id: 'creator-like-sub',
      name: '"Like & Subscribe" Pill',
      category: 'creator',
      description: 'Combined Like & Subscribe action pill',
      duration: 3.5,
      fps: 60,
      title: 'LIKE & SUBSCRIBE',
      subtitle: 'INTERACT',
      primaryColor: '#dc2626',
      secondaryColor: '#38bdf8',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-comment-cta',
    name: 'Comment CTA Bubble',
    category: 'creator',
    description: 'Speech bubble callout encouraging viewers to share thoughts in comments.',
    render: renderCreatorCommentCta,
    defaultConfig: {
      id: 'creator-comment-cta',
      name: 'Comment CTA Bubble',
      category: 'creator',
      description: 'Animated chat bubble prompt for comments',
      duration: 3.5,
      fps: 60,
      title: 'WHAT DO YOU THINK?',
      subtitle: 'Drop your thoughts in the comments below!',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-video-intro',
    name: 'New Video Opener',
    category: 'creator',
    description: 'High-energy bold title opener with episode tag pill and subtext.',
    render: renderCreatorVideoIntro,
    defaultConfig: {
      id: 'creator-video-intro',
      name: 'New Video Opener',
      category: 'creator',
      description: 'Punchy creator video title opener',
      duration: 3.5,
      fps: 60,
      title: 'THE ULTIMATE CREATOR SETUP',
      subtitle: 'Episode 42 • Full Studio Tour',
      badgeText: 'NEW EPISODE',
      primaryColor: '#ec4899',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-chapter-title',
    name: 'Chapter Title Slug',
    category: 'creator',
    description: 'YouTube segment title banner with timecode timestamp and bold title.',
    render: renderCreatorChapterTitle,
    defaultConfig: {
      id: 'creator-chapter-title',
      name: 'Chapter Title Slug',
      category: 'creator',
      description: 'Video chapter title banner with timestamp',
      duration: 3.0,
      fps: 60,
      title: 'Phase 2: Hardware Architecture',
      subtitle: 'Chapter 2',
      dateText: '04:15',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-coming-up',
    name: '"Coming up..." Teaser',
    category: 'creator',
    description: 'Attention-grabbing hook card teasing the climax of the video.',
    render: renderCreatorComingUp,
    defaultConfig: {
      id: 'creator-coming-up',
      name: '"Coming up..." Teaser',
      category: 'creator',
      description: 'Video teaser hook card',
      duration: 3.0,
      fps: 60,
      title: 'The $10,000 Blind Camera Test',
      subtitle: 'Coming up next',
      primaryColor: '#f59e0b',
      secondaryColor: '#ffffff',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: '#0f172a',
      enableSFX: true,
    },
  },
  {
    id: 'creator-previously',
    name: '"Previously..." Recap',
    category: 'creator',
    description: 'Rewind recap banner for serialized videos and story series.',
    render: renderCreatorPreviously,
    defaultConfig: {
      id: 'creator-previously',
      name: '"Previously..." Recap',
      category: 'creator',
      description: 'Previous episode recap banner',
      duration: 3.0,
      fps: 60,
      title: 'We Built an AI Automation Farm',
      subtitle: 'Previously on the channel',
      primaryColor: '#38bdf8',
      secondaryColor: '#ffffff',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(10, 10, 15, 0.9)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-meanwhile',
    name: '"Meanwhile..." Card',
    category: 'creator',
    description: 'Bold comic/meme narrative transition card with pop bounce.',
    render: renderCreatorMeanwhile,
    defaultConfig: {
      id: 'creator-meanwhile',
      name: '"Meanwhile..." Card',
      category: 'creator',
      description: 'Comic narrative jump card',
      duration: 2.0,
      fps: 60,
      title: 'MEANWHILE...',
      subtitle: 'CUTAWAY',
      primaryColor: '#facc15',
      secondaryColor: '#000000',
      accentColor: '#000000',
      textColor: '#000000',
      cardColor: '#facc15',
      enableSFX: true,
    },
  },
  {
    id: 'creator-pov',
    name: '"POV:" Sticker',
    category: 'creator',
    description: 'Viral TikTok/Reels POV title card with bold contrast styling.',
    render: renderCreatorPov,
    defaultConfig: {
      id: 'creator-pov',
      name: '"POV:" Sticker',
      category: 'creator',
      description: 'POV title card for short-form content',
      duration: 3.0,
      fps: 60,
      title: 'You just found the ultimate free motion graphics app',
      subtitle: 'POV',
      primaryColor: '#ec4899',
      secondaryColor: '#ffffff',
      accentColor: '#ec4899',
      textColor: '#ffffff',
      cardColor: 'rgba(0, 0, 0, 0.85)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-did-you-know',
    name: '"Did you know?" Card',
    category: 'creator',
    description: 'Curiosity fact card with lightbulb badge and lead facts.',
    render: renderCreatorDidYouKnow,
    defaultConfig: {
      id: 'creator-did-you-know',
      name: '"Did you know?" Card',
      category: 'creator',
      description: 'Curiosity trivia fact card with glowing badge',
      duration: 3.5,
      fps: 60,
      title: 'Over 82% of all internet traffic is video content.',
      subtitle: 'Adding animated motion graphics increases audience retention by 3.4x.',
      primaryColor: '#38bdf8',
      secondaryColor: '#6366f1',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-fact-card',
    name: 'Quick Fact Card',
    category: 'creator',
    description: 'Editorial verified fact card with green verification bar.',
    render: renderCreatorFactCard,
    defaultConfig: {
      id: 'creator-fact-card',
      name: 'Quick Fact Card',
      category: 'creator',
      description: 'Verified information fact card',
      duration: 3.5,
      fps: 60,
      title: 'Human Attention Spans Peak in First 3 Seconds',
      subtitle: 'Hooks and motion callouts prevent drop-off before the mid-roll.',
      primaryColor: '#22c55e',
      secondaryColor: '#38bdf8',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: 'rgba(10, 15, 29, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-top-5',
    name: 'Top 5 List Ranking',
    category: 'creator',
    description: 'Animated numbered countdown list ranking #1 to #5 with staggered entrances.',
    render: renderCreatorTop5,
    defaultConfig: {
      id: 'creator-top-5',
      name: 'Top 5 List Ranking',
      category: 'creator',
      description: 'Top 5 ranking list graphic',
      duration: 4.0,
      fps: 60,
      title: 'TOP 5 CREATOR TOOLS',
      subtitle: 'Rankings',
      primaryColor: '#6366f1',
      secondaryColor: '#f59e0b',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'creator-countdown',
    name: 'Cinematic Countdown',
    category: 'creator',
    description: 'Large 5-4-3-2-1 circular countdown ring with audio ticking.',
    render: renderCreatorCountdown,
    defaultConfig: {
      id: 'creator-countdown',
      name: 'Cinematic Countdown',
      category: 'creator',
      description: 'Circular ticking countdown 5 to 1',
      duration: 5.0,
      fps: 60,
      title: 'COUNTDOWN',
      subtitle: 'START',
      primaryColor: '#dc2626',
      secondaryColor: '#ffffff',
      accentColor: '#dc2626',
      textColor: '#ffffff',
      cardColor: '#000000',
      enableSFX: true,
    },
  },
  {
    id: 'creator-reaction-popup',
    name: 'Emoji Reaction Cluster',
    category: 'creator',
    description: 'Huge bouncy emoji reaction burst (😱 🔥 🤯) for funny or shocked moments.',
    render: renderCreatorReactionPopup,
    defaultConfig: {
      id: 'creator-reaction-popup',
      name: 'Emoji Reaction Cluster',
      category: 'creator',
      description: 'Bouncing animated emoji cluster',
      duration: 2.0,
      fps: 60,
      title: 'REACTION',
      subtitle: 'EMOJI',
      primaryColor: '#f59e0b',
      secondaryColor: '#ec4899',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: 'transparent',
      enableSFX: true,
    },
  },
  {
    id: 'creator-meme-popup',
    name: 'Meme-Style Text Pop',
    category: 'creator',
    description: 'Retro impact-font meme text sticker with outline and shake.',
    render: renderCreatorMemePopup,
    defaultConfig: {
      id: 'creator-meme-popup',
      name: 'Meme-Style Text Pop',
      category: 'creator',
      description: 'Impact font meme text sticker',
      duration: 2.0,
      fps: 60,
      title: 'WAIT... WHAT?!',
      subtitle: 'MEME',
      primaryColor: '#ffffff',
      secondaryColor: '#000000',
      accentColor: '#000000',
      textColor: '#ffffff',
      cardColor: 'transparent',
      enableSFX: true,
    },
  },
  {
    id: 'creator-end-screen',
    name: 'Creator End Screen',
    category: 'creator',
    description: 'Modular YouTube end slate with next video, playlist cards, and subscribe circle.',
    render: renderCreatorEndScreen,
    defaultConfig: {
      id: 'creator-end-screen',
      name: 'Creator End Screen',
      category: 'creator',
      description: 'YouTube end screen video layout',
      duration: 4.0,
      fps: 60,
      title: 'THANKS FOR WATCHING',
      subtitle: 'END SLATE',
      primaryColor: '#dc2626',
      secondaryColor: '#6366f1',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.9)',
      enableSFX: true,
    },
  },
];

// ==========================================
// COMMERCIAL / ADVERTISING TEMPLATES (13)
// ==========================================
export const COMMERCIAL_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'comm-product-reveal',
    name: 'Product Reveal Spotlight',
    category: 'commercial',
    description: 'Spotlight beam opening on product launch card with price and CTA button.',
    render: renderCommProductReveal,
    defaultConfig: {
      id: 'comm-product-reveal',
      name: 'Product Reveal Spotlight',
      category: 'commercial',
      description: 'Product reveal showcase with spotlight and pricing',
      duration: 3.5,
      fps: 60,
      title: 'ULTRA SOUND PRO X',
      subtitle: 'Active noise cancellation • 48hr battery',
      productPrice: '$199',
      ctaText: 'ORDER NOW ➔',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      enableSFX: true,
    },
  },
  {
    id: 'comm-product-showcase',
    name: 'Product Specs Showcase',
    category: 'commercial',
    description: 'Three key specifications cards highlighted with icons and descriptions.',
    render: renderCommProductShowcase,
    defaultConfig: {
      id: 'comm-product-showcase',
      name: 'Product Specs Showcase',
      category: 'commercial',
      description: 'Product specs highlight grid',
      duration: 3.5,
      fps: 60,
      title: 'ENGINEERED FOR SUPREMACY',
      subtitle: '3 KEY SPECS',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'comm-price-tag',
    name: 'Price Tag Slashed',
    category: 'commercial',
    description: 'Bouncing price tag with strikethrough original price and discount figure.',
    render: renderCommPriceTag,
    defaultConfig: {
      id: 'comm-price-tag',
      name: 'Price Tag Slashed',
      category: 'commercial',
      description: 'Slashed discount price tag card',
      duration: 3.0,
      fps: 60,
      title: 'SPECIAL OFFER',
      subtitle: 'LIMITED TIME',
      originalPrice: '$99.00',
      productPrice: '$49.00',
      primaryColor: '#22c55e',
      secondaryColor: '#ef4444',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: '#0f172a',
      enableSFX: true,
    },
  },
  {
    id: 'comm-discount-badge',
    name: 'Discount Seal Badge',
    category: 'commercial',
    description: '3D bouncing starburst discount seal showing percentage off.',
    render: renderCommDiscountBadge,
    defaultConfig: {
      id: 'comm-discount-badge',
      name: 'Discount Seal Badge',
      category: 'commercial',
      description: '3D discount starburst seal',
      duration: 2.5,
      fps: 60,
      title: 'DISCOUNT',
      subtitle: 'SALE',
      discountPercent: '50%',
      primaryColor: '#dc2626',
      secondaryColor: '#ffffff',
      accentColor: '#ffffff',
      textColor: '#ffffff',
      cardColor: '#dc2626',
      enableSFX: true,
    },
  },
  {
    id: 'comm-sale-anim',
    name: 'Flash Sale Ribbon',
    category: 'commercial',
    description: 'Full-width animated red sale ribbon with bold diagonal safety stripes.',
    render: renderCommSaleAnim,
    defaultConfig: {
      id: 'comm-sale-anim',
      name: 'Flash Sale Ribbon',
      category: 'commercial',
      description: 'Flash sale banner with diagonal stripes',
      duration: 3.0,
      fps: 60,
      title: 'FLASH SALE',
      subtitle: 'DEALS',
      saleTitle: 'FLASH SALE • UP TO 70% OFF',
      primaryColor: '#dc2626',
      secondaryColor: '#b91c1c',
      accentColor: '#ffffff',
      textColor: '#ffffff',
      cardColor: '#dc2626',
      enableSFX: true,
    },
  },
  {
    id: 'comm-feature-callout',
    name: 'Feature Callout Pointer',
    category: 'commercial',
    description: 'Pointer pin with animated elbow line pointing to a specific product detail.',
    render: renderCommFeatureCallout,
    defaultConfig: {
      id: 'comm-feature-callout',
      name: 'Feature Callout Pointer',
      category: 'commercial',
      description: 'Pointer line callout to feature detail',
      duration: 3.0,
      fps: 60,
      title: 'Aerospace Alloy Frame',
      subtitle: 'Lightweight & Rigid',
      primaryColor: '#38bdf8',
      secondaryColor: '#6366f1',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'comm-product-comparison',
    name: 'Comparison Grid',
    category: 'commercial',
    description: 'Side-by-side "Us vs. Them" feature comparison grid with green checkmarks.',
    render: renderCommProductComparison,
    defaultConfig: {
      id: 'comm-product-comparison',
      name: 'Comparison Grid',
      category: 'commercial',
      description: 'Us vs Them comparison checkmark grid',
      duration: 4.0,
      fps: 60,
      title: 'MOTIONFORGE',
      subtitle: 'VS COMPETITORS',
      primaryColor: '#6366f1',
      secondaryColor: '#22c55e',
      accentColor: '#ef4444',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'comm-product-rotation',
    name: '360° Product Rotation',
    category: 'commercial',
    description: 'Isometric spinning pedestal showcasing full 360 view of your product.',
    render: renderCommProductRotation,
    defaultConfig: {
      id: 'comm-product-rotation',
      name: '360° Product Rotation',
      category: 'commercial',
      description: 'Rotating product display on pedestal',
      duration: 4.0,
      fps: 60,
      title: '360° INTERACTIVE VIEW',
      subtitle: 'Explore every angle',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'comm-benefits-list',
    name: 'Benefits Checklist',
    category: 'commercial',
    description: 'Animated checklist with glowing green checkmarks highlighting key value propositions.',
    render: renderCommBenefitsList,
    defaultConfig: {
      id: 'comm-benefits-list',
      name: 'Benefits Checklist',
      category: 'commercial',
      description: 'Key benefits checklist with checkmarks',
      duration: 4.0,
      fps: 60,
      title: 'WHY CHOOSE MOTIONFORGE?',
      subtitle: 'Value Props',
      primaryColor: '#22c55e',
      secondaryColor: '#6366f1',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'comm-cta-banner',
    name: 'High-Conversion CTA Banner',
    category: 'commercial',
    description: 'Vibrant gradient bottom banner with headline and clickable style button.',
    render: renderCommCtaBanner,
    defaultConfig: {
      id: 'comm-cta-banner',
      name: 'High-Conversion CTA Banner',
      category: 'commercial',
      description: 'Gradient commercial call-to-action banner',
      duration: 3.5,
      fps: 60,
      title: 'LIMITED OFFER: GET 50% OFF',
      subtitle: 'Call to action',
      ctaText: 'CLAIM NOW ➔',
      primaryColor: '#6366f1',
      secondaryColor: '#ec4899',
      accentColor: '#ffffff',
      textColor: '#ffffff',
      cardColor: '#6366f1',
      enableSFX: true,
    },
  },
  {
    id: 'comm-app-reveal',
    name: 'Smartphone App Reveal',
    category: 'commercial',
    description: 'Modern smartphone frame mockup sliding in with live app interface preview.',
    render: renderCommAppReveal,
    defaultConfig: {
      id: 'comm-app-reveal',
      name: 'Smartphone App Reveal',
      category: 'commercial',
      description: 'Smartphone app frame reveal mockup',
      duration: 3.5,
      fps: 60,
      title: 'NOW AVAILABLE ON MOBILE',
      subtitle: 'Download on iOS and Android today',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: '#0f172a',
      enableSFX: true,
    },
  },
  {
    id: 'comm-qr-code',
    name: 'QR Code with Scanner',
    category: 'commercial',
    description: 'Scanning red laser line sweeping across QR code card with "Scan to Order".',
    render: renderCommQrCode,
    defaultConfig: {
      id: 'comm-qr-code',
      name: 'QR Code with Scanner',
      category: 'commercial',
      description: 'Scannable QR code card with animated laser sweep',
      duration: 3.5,
      fps: 60,
      title: 'SCAN TO ORDER',
      subtitle: 'QR Code',
      primaryColor: '#ef4444',
      secondaryColor: '#0f172a',
      accentColor: '#ef4444',
      textColor: '#0f172a',
      cardColor: '#ffffff',
      enableSFX: true,
    },
  },
  {
    id: 'comm-testimonial-card',
    name: 'Customer Review Card',
    category: 'commercial',
    description: 'Verified 5-star customer review card with quote, author name, and company role.',
    render: renderCommTestimonialCard,
    defaultConfig: {
      id: 'comm-testimonial-card',
      name: 'Customer Review Card',
      category: 'commercial',
      description: '5-star testimonial card with customer quote',
      duration: 3.5,
      fps: 60,
      title: 'David Miller',
      subtitle: 'VP of Growth • TechFlow',
      quoteText: '“The best investment we made for our marketing team this year.”',
      primaryColor: '#f59e0b',
      secondaryColor: '#38bdf8',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
];

// ==========================================
// MONEY & CURRENCY TEMPLATES (10)
// ==========================================
export const MONEY_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'money-coin-flip',
    name: '3D Gold Coin Flip',
    category: 'money',
    description: 'Kinetic 3D spinning metallic gold coin with embossed currency symbol, shine glint, and metallic clink SFX.',
    render: renderMoneyCoinFlip,
    defaultConfig: {
      id: 'money-coin-flip',
      name: '3D Gold Coin Flip',
      category: 'money',
      description: 'Spinning 3D gold coin with customizable symbol',
      duration: 3.5,
      fps: 60,
      title: 'FORTUNE AWAITS',
      subtitle: '₹ 10,00,000 WEALTH POOL',
      currencySymbol: '₹',
      primaryColor: '#eab308',
      secondaryColor: '#ca8a04',
      accentColor: '#fde047',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-falling-coins',
    name: 'Gold Coin Shower',
    category: 'money',
    description: 'Raining cascade of tumbling 3D gold coins with depth-of-field, jackpot badge, and coin shower SFX.',
    render: renderMoneyFallingCoins,
    defaultConfig: {
      id: 'money-falling-coins',
      name: 'Gold Coin Shower',
      category: 'money',
      description: 'Falling gold coins jackpot animation',
      duration: 3.5,
      fps: 60,
      title: 'JACKPOT WINNER!',
      subtitle: '₹ 1,00,00,000 CASH PRIZE',
      currencySymbol: '₹',
      primaryColor: '#eab308',
      secondaryColor: '#ca8a04',
      accentColor: '#fde047',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.92)',
      enableSFX: true,
    },
  },
  {
    id: 'money-banknote-stack',
    name: 'Floating Banknotes Stack',
    category: 'money',
    description: 'Layered 3D currency notes floating with security threads, denomination watermark, and cash rustle SFX.',
    render: renderMoneyBanknoteStack,
    defaultConfig: {
      id: 'money-banknote-stack',
      name: 'Floating Banknotes Stack',
      category: 'money',
      description: 'Floating stack of currency notes',
      duration: 3.5,
      fps: 60,
      title: 'CASH FLOW EMPIRE',
      subtitle: 'UNLIMITED LIQUIDITY ON DEMAND',
      currencySymbol: '₹',
      denomination: '500',
      primaryColor: '#0d9488',
      secondaryColor: '#115e59',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-rupee-title',
    name: 'Cinematic ₹ Rupee Reveal',
    category: 'money',
    description: 'Giant luminous ₹ Rupee symbol bursting onto screen with radial gold flare, serif typography, and sting SFX.',
    render: renderMoneyRupeeTitle,
    defaultConfig: {
      id: 'money-rupee-title',
      name: 'Cinematic ₹ Rupee Reveal',
      category: 'money',
      description: 'Luminous ₹ Rupee big title reveal',
      duration: 3.5,
      fps: 60,
      title: '₹ 1,00,00,000',
      subtitle: 'ONE CRORE MILESTONE UNLOCKED',
      currencySymbol: '₹',
      primaryColor: '#eab308',
      secondaryColor: '#f59e0b',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-wealth-counter',
    name: 'Dynamic Revenue Ticker',
    category: 'money',
    description: 'Fast-paced roll-up revenue ticker with live green growth badge and ticking count-up SFX.',
    render: renderMoneyWealthCounter,
    defaultConfig: {
      id: 'money-wealth-counter',
      name: 'Dynamic Revenue Ticker',
      category: 'money',
      description: 'Fast roll-up revenue counter with growth badge',
      duration: 3.5,
      fps: 60,
      title: 'ARR Goal Reached',
      subtitle: 'ARR Goal Reached 30 Days Ahead of Schedule',
      currencySymbol: '₹',
      amountNumber: 5000000,
      primaryColor: '#22c55e',
      secondaryColor: '#16a34a',
      accentColor: '#4ade80',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-cash-explosion',
    name: 'Cash & Confetti Explosion',
    category: 'money',
    description: 'Explosive burst of flying currency bills, gold coins, and impact badge with cash register ring SFX.',
    render: renderMoneyCashExplosion,
    defaultConfig: {
      id: 'money-cash-explosion',
      name: 'Cash & Confetti Explosion',
      category: 'money',
      description: 'Explosion of cash and coins with impact badge',
      duration: 3.5,
      fps: 60,
      title: 'BIG MONEY SHOT!',
      subtitle: '₹ 50 LAKHS BOUNTY CLAIMED',
      currencySymbol: '₹',
      primaryColor: '#dc2626',
      secondaryColor: '#b91c1c',
      accentColor: '#fef08a',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-crypto-coin',
    name: 'Glowing Web3 Crypto Token',
    category: 'money',
    description: 'Cyberpunk rotating digital currency coin with neon circuit pattern, glowing aura, and tech ticker.',
    render: renderMoneyCryptoCoin,
    defaultConfig: {
      id: 'money-crypto-coin',
      name: 'Glowing Web3 Crypto Token',
      category: 'money',
      description: 'Spinning digital crypto token with circuits',
      duration: 3.5,
      fps: 60,
      title: 'WEB3 TOKEN MINT',
      subtitle: 'CIRCULATING SUPPLY: 1,000,000,000',
      currencySymbol: '₿',
      primaryColor: '#6366f1',
      secondaryColor: '#a855f7',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-piggy-bank',
    name: 'Savings & Investment Goal',
    category: 'money',
    description: 'Modern animated savings goal bar tracking target amount with percentage milestone chime.',
    render: renderMoneyPiggyBank,
    defaultConfig: {
      id: 'money-piggy-bank',
      name: 'Savings & Investment Goal',
      category: 'money',
      description: 'Savings goal progress bar with milestone fill',
      duration: 3.5,
      fps: 60,
      title: 'ANNUAL SAVINGS GOAL',
      subtitle: 'Target 25 Lakhs',
      currencySymbol: '₹',
      amountNumber: 2500000,
      primaryColor: '#06b6d4',
      secondaryColor: '#3b82f6',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-transaction-pill',
    name: 'Payment Received Toast',
    category: 'money',
    description: 'Sleek fintech push notification toast (UPI / Apple Pay / NetBanking) with smooth payment chime.',
    render: renderMoneyTransactionPill,
    defaultConfig: {
      id: 'money-transaction-pill',
      name: 'Payment Received Toast',
      category: 'money',
      description: 'Fintech transaction received notification alert',
      duration: 3.5,
      fps: 60,
      title: '₹ 50,000 Received',
      subtitle: 'Payment transferred via UPI / Bank Wire',
      currencySymbol: '₹',
      primaryColor: '#22c55e',
      secondaryColor: '#16a34a',
      accentColor: '#4ade80',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.96)',
      enableSFX: true,
    },
  },
  {
    id: 'money-net-worth',
    name: 'Portfolio Net Worth Card',
    category: 'money',
    description: 'Executive wealth breakdown card featuring total valuation, equity allocations, and positive return badges.',
    render: renderMoneyNetWorth,
    defaultConfig: {
      id: 'money-net-worth',
      name: 'Portfolio Net Worth Card',
      category: 'money',
      description: 'Luxury executive portfolio net worth display',
      duration: 3.5,
      fps: 60,
      title: '₹ 8,50,00,000',
      subtitle: 'PORTFOLIO NET WORTH',
      currencySymbol: '₹',
      primaryColor: '#eab308',
      secondaryColor: '#ca8a04',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: 'rgba(10, 15, 29, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-indian-note-showcase',
    name: 'Indian Note 3D Showcase',
    category: 'money',
    description: '3D tilting showcase of authentic Indian currency (₹2000, ₹500, ₹200, ₹100, ₹50) with security thread & Gandhi watermark.',
    render: renderMoneyIndianNoteShowcase,
    defaultConfig: {
      id: 'money-indian-note-showcase',
      name: 'Indian Note 3D Showcase',
      category: 'money',
      description: '3D tilting Indian note specimen showcase',
      duration: 3.5,
      fps: 60,
      title: 'INDIAN ₹500 SPECIMEN NOTE',
      subtitle: 'पाँच सौ रुपये • FIVE HUNDRED RUPEES',
      currencySymbol: '₹',
      denomination: '500',
      primaryColor: '#475569',
      secondaryColor: '#1e293b',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-cash-fanning',
    name: 'Indian Cash Fan Spread',
    category: 'money',
    description: 'Dynamic spread of 7 Indian currency notes fanning out like playing cards with realistic paper rustle SFX.',
    render: renderMoneyCashFanning,
    defaultConfig: {
      id: 'money-cash-fanning',
      name: 'Indian Cash Fan Spread',
      category: 'money',
      description: 'Fanned spread of 7 Indian notes',
      duration: 3.5,
      fps: 60,
      title: '₹ 50,000 CASH SPREAD',
      subtitle: 'HIGH-ROLLER FINANCES • 100% SPECIMEN ENTERTAINMENT',
      currencySymbol: '₹',
      denomination: '500',
      primaryColor: '#475569',
      secondaryColor: '#1e293b',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'money-indian-notes-bundle',
    name: 'Indian Notes Cash Bundle',
    category: 'money',
    description: '100-note bank-strapped wad of Indian Rupee bills with official paper currency band and cash rustle SFX.',
    render: renderMoneyIndianNotesBundle,
    defaultConfig: {
      id: 'money-indian-notes-bundle',
      name: 'Indian Notes Cash Bundle',
      category: 'money',
      description: 'Bank-strapped bundle of 100 Indian notes',
      duration: 3.5,
      fps: 60,
      title: '₹50,000 CASH BUNDLE',
      subtitle: '100 NOTES OF ₹500 • ENTERTAINMENT PROP SAMPLE',
      currencySymbol: '₹',
      denomination: '500',
      primaryColor: '#475569',
      secondaryColor: '#1e293b',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
];

