import type { TemplateConfig, RenderContext } from '../types/template';
import { renderBarChart } from './barChart';
import { renderLineChart } from './lineChart';
import { renderPieChart3D } from './pieChart3D';
import { renderRadialDonut } from './radialDonut';
import { renderHorizontalBar } from './horizontalBar';
import { renderGaugeMeter } from './gaugeMeter';
import { renderMetricCounter } from './metricCounter';
import { renderGoalProgress } from './goalProgress';
import { renderStarReview } from './starReview';
import { renderLowerThird } from './lowerThird';
import { renderBreakingNews } from './breakingNews';
import { renderCyberpunkHUD } from './cyberpunkHUD';
import { renderSocialCallout } from './socialCallout';
import { renderYouTubeAction } from './youtubeAction';
import { renderInstagramPop } from './instagramPop';
import { renderFacebookReaction } from './facebookReaction';
import { renderTikTokPop } from './tiktokPop';
import { renderTwitterCallout } from './twitterCallout';

export interface TemplateDefinition {
  id: string;
  name: string;
  description: string;
  category: 'chart' | 'metric' | 'title' | 'social';
  defaultConfig: TemplateConfig;
  render: (rc: RenderContext) => void;
}

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: 'bar-chart',
    name: 'Growth Bar Chart',
    category: 'chart',
    description: 'Dynamic rising bars with glowing gradient fills, value tags, and category labels.',
    render: renderBarChart,
    defaultConfig: {
      id: 'bar-chart',
      name: 'Growth Bar Chart',
      category: 'chart',
      description: 'Animated rising bars with glowing gradients',
      duration: 3.5,
      fps: 60,
      title: 'Monthly Revenue Growth',
      subtitle: 'Q1 - Q2 Performance Overview',
      badgeText: '+42% YoY',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#a855f7',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      prefix: '$',
      suffix: 'k',
      chartData: [
        { id: '1', label: 'Jan', value: 45, color: '#38bdf8' },
        { id: '2', label: 'Feb', value: 72, color: '#6366f1' },
        { id: '3', label: 'Mar', value: 58, color: '#818cf8' },
        { id: '4', label: 'Apr', value: 94, color: '#a855f7' },
        { id: '5', label: 'May', value: 85, color: '#ec4899' },
      ],
    },
  },
  {
    id: 'line-chart',
    name: 'Smooth Curve Graph',
    category: 'chart',
    description: 'Animated smooth Bezier curve drawing with glowing data points and area gradient underfill.',
    render: renderLineChart,
    defaultConfig: {
      id: 'line-chart',
      name: 'Smooth Curve Graph',
      category: 'chart',
      description: 'Animated path drawing with glowing milestone tags',
      duration: 3.5,
      fps: 60,
      title: 'Active Subscriber Trend',
      subtitle: 'Trailing 6 Quarters Velocity',
      primaryColor: '#38bdf8',
      secondaryColor: '#6366f1',
      accentColor: '#06b6d4',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      prefix: '',
      suffix: 'k',
      chartData: [
        { id: '1', label: 'Q1', value: 30 },
        { id: '2', label: 'Q2', value: 65 },
        { id: '3', label: 'Q3', value: 50 },
        { id: '4', label: 'Q4', value: 95 },
        { id: '5', label: 'Q5', value: 85 },
        { id: '6', label: 'Q6', value: 135 },
      ],
    },
  },
  {
    id: 'pie-chart-3d',
    name: '3D Pie Chart',
    category: 'chart',
    description: 'Isometric 3D extruded pie chart with glossy bevels, rotational entrance, and floating badges.',
    render: renderPieChart3D,
    defaultConfig: {
      id: 'pie-chart-3d',
      name: '3D Pie Chart',
      category: 'chart',
      description: 'Extruded 3D pie breakdown with glossy highlights',
      duration: 3.5,
      fps: 60,
      title: 'Market Share Breakdown',
      subtitle: 'Annual Revenue Segment Distribution',
      badgeText: '3D ISOMETRIC',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#a855f7',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      prefix: '$',
      suffix: 'M',
      chartData: [
        { id: '1', label: 'Product & AI', value: 42, color: '#6366f1' },
        { id: '2', label: 'Marketing', value: 28, color: '#38bdf8' },
        { id: '3', label: 'Operations', value: 18, color: '#a855f7' },
        { id: '4', label: 'Sales & BD', value: 12, color: '#ec4899' },
      ],
    },
  },
  {
    id: 'radial-donut',
    name: 'Radial Donut Rings',
    category: 'chart',
    description: 'Concentric glowing activity rings with glowing head particles, center metric, and breakdown cards.',
    render: renderRadialDonut,
    defaultConfig: {
      id: 'radial-donut',
      name: 'Radial Donut Rings',
      category: 'chart',
      description: 'Concentric goal and activity progress rings',
      duration: 3.5,
      fps: 60,
      title: 'Performance Goals',
      subtitle: 'Daily target completion overview',
      badgeText: 'TARGET 100%',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#ec4899',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      chartData: [
        { id: '1', label: 'Active Energy', value: 85, color: '#6366f1' },
        { id: '2', label: 'Workout Goal', value: 68, color: '#38bdf8' },
        { id: '3', label: 'Consistency', value: 92, color: '#ec4899' },
      ],
    },
  },
  {
    id: 'metric-counter',
    name: 'Metric Counter Odometer',
    category: 'metric',
    description: 'High-impact rolling counter roll-up with prefix/suffix, trend badge, and accent progress line.',
    render: renderMetricCounter,
    defaultConfig: {
      id: 'metric-counter',
      name: 'Metric Counter Odometer',
      category: 'metric',
      description: 'Smooth rolling counter for KPIs, revenue, or followers',
      duration: 3.0,
      fps: 60,
      title: 'Total Community Members',
      subtitle: 'Joined across all channels this month',
      badgeText: '+28.4% this week',
      primaryColor: '#6366f1',
      secondaryColor: '#ec4899',
      accentColor: '#38bdf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      metricStart: 12000,
      metricEnd: 84520,
      prefix: '',
      suffix: ' devs',
    },
  },
  {
    id: 'lower-third',
    name: 'Cinematic Lower Third',
    category: 'title',
    description: 'Broadcast-quality name and topic banner with animated vertical accent line and horizontal wipe.',
    render: renderLowerThird,
    defaultConfig: {
      id: 'lower-third',
      name: 'Cinematic Lower Third',
      category: 'title',
      description: 'Clean name and title overlay for video interviews and talks',
      duration: 3.5,
      fps: 60,
      title: 'Alex Rivera',
      subtitle: 'Lead Motion & VFX Designer',
      badgeText: 'SPEAKER',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#818cf8',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
    },
  },
  {
    id: 'social-callout',
    name: 'YouTube Subscribe Pop',
    category: 'social',
    description: 'Animated subscribe callout with avatar, button click pulse, subscribed state, and ringing bell.',
    render: renderSocialCallout,
    defaultConfig: {
      id: 'social-callout',
      name: 'YouTube Subscribe Pop',
      category: 'social',
      description: 'Subscribe button with click bounce and ringing bell',
      duration: 3.5,
      fps: 60,
      title: 'MotionForge Studio',
      subtitle: '1.45M subscribers',
      avatarText: 'MF',
      subscriberCount: '1.45M',
      primaryColor: '#ef4444',
      secondaryColor: '#f97316',
      accentColor: '#fbbf24',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'youtube-action',
    name: 'YouTube Action Bar',
    category: 'social',
    description: 'YouTube 3-in-1 overlay with animated Like button, Subscribe button, and Bell chime SFX.',
    render: renderYouTubeAction,
    defaultConfig: {
      id: 'youtube-action',
      name: 'YouTube Action Bar',
      category: 'social',
      description: 'Like, Subscribe & Bell notification overlay with synchronized SFX',
      duration: 3.5,
      fps: 60,
      title: 'MotionForge Studio',
      subtitle: '1.48M subscribers',
      avatarText: 'MF',
      subscriberCount: '1.48M',
      primaryColor: '#ff0000',
      secondaryColor: '#38bdf8',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'instagram-pop',
    name: 'Instagram Follow & Like',
    category: 'social',
    description: 'Instagram Reel/Post follow banner with rainbow gradient story ring, verified badge, and popping heart SFX.',
    render: renderInstagramPop,
    defaultConfig: {
      id: 'instagram-pop',
      name: 'Instagram Follow & Like',
      category: 'social',
      description: 'Instagram double-tap heart pop and follow button with audio SFX',
      duration: 3.5,
      fps: 60,
      title: 'motion.creator',
      handle: '@motion.creator',
      subtitle: '320K followers',
      avatarText: 'IG',
      subscriberCount: '320K',
      primaryColor: '#d62976',
      secondaryColor: '#fa7e1e',
      accentColor: '#0095f6',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'facebook-reaction',
    name: 'Facebook Reaction Bar',
    category: 'social',
    description: 'Facebook floating reactions (Like, Love, Care, Haha) with follow button and reaction pop SFX.',
    render: renderFacebookReaction,
    defaultConfig: {
      id: 'facebook-reaction',
      name: 'Facebook Reaction Bar',
      category: 'social',
      description: 'Facebook floating reaction bubbles and page follow banner',
      duration: 3.5,
      fps: 60,
      title: 'MotionForge Official',
      subtitle: '620K followers',
      avatarText: 'FB',
      subscriberCount: '620K',
      primaryColor: '#1877f2',
      secondaryColor: '#fa3e3e',
      accentColor: '#f7b125',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'horizontal-bar',
    name: 'Horizontal Comparison Bar',
    category: 'chart',
    description: 'Horizontal ranking & benchmark bars with glowing gradients and percentage values.',
    render: renderHorizontalBar,
    defaultConfig: {
      id: 'horizontal-bar',
      name: 'Horizontal Comparison Bar',
      category: 'chart',
      description: 'Horizontal benchmark and comparison bars',
      duration: 3.5,
      fps: 60,
      title: 'Performance Benchmark',
      subtitle: 'Rendering Speed & Efficiency Score',
      badgeText: '+3.4x Faster',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#a855f7',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      suffix: '%',
      chartData: [
        { id: '1', label: 'MotionForge', value: 96, color: '#6366f1' },
        { id: '2', label: 'After Effects', value: 74, color: '#38bdf8' },
        { id: '3', label: 'Canva Pro', value: 65, color: '#a855f7' },
        { id: '4', label: 'CapCut Web', value: 52, color: '#ec4899' },
      ],
    },
  },
  {
    id: 'gauge-meter',
    name: 'Speedometer Gauge',
    category: 'chart',
    description: 'Radial curved speedometer gauge with sweeping glowing arc, needle, and load badge.',
    render: renderGaugeMeter,
    defaultConfig: {
      id: 'gauge-meter',
      name: 'Speedometer Gauge',
      category: 'chart',
      description: 'Dynamic load and performance speedometer gauge',
      duration: 3.5,
      fps: 60,
      title: 'System Health & Load',
      subtitle: 'Real-time performance throughput',
      badgeText: 'Optimal (99.4%)',
      metricEnd: 88,
      suffix: '%',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#ec4899',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
    },
  },
  {
    id: 'goal-progress',
    name: 'Revenue Goal Milestone',
    category: 'metric',
    description: 'High-impact revenue milestone bar filling with sparkle pulse, target badge, and counter.',
    render: renderGoalProgress,
    defaultConfig: {
      id: 'goal-progress',
      name: 'Revenue Goal Milestone',
      category: 'metric',
      description: 'Revenue goal tracker bar with glowing fill and sparkles',
      duration: 3.5,
      fps: 60,
      title: 'Annual ARR Goal',
      subtitle: 'Series A Milestone Tracking',
      badgeText: 'Goal: $1.0M',
      metricStart: 780000,
      metricEnd: 1000000,
      prefix: '$',
      primaryColor: '#6366f1',
      secondaryColor: '#38bdf8',
      accentColor: '#a855f7',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      enableSFX: true,
    },
  },
  {
    id: 'star-review',
    name: '5-Star Rating Card',
    category: 'metric',
    description: 'Golden glowing 5-star rating cascade with score counter, customer quote, and verified badge.',
    render: renderStarReview,
    defaultConfig: {
      id: 'star-review',
      name: '5-Star Rating Card',
      category: 'metric',
      description: '5 glowing golden review stars cascade with rating score',
      duration: 3.5,
      fps: 60,
      title: '"This tool transformed our video production workflow in minutes!"',
      subtitle: 'Sarah Jenkins — Lead Motion Designer at TechCorp',
      badgeText: 'VERIFIED 5-STAR REVIEW',
      primaryColor: '#f59e0b',
      secondaryColor: '#fbbf24',
      accentColor: '#22c55e',
      textColor: '#ffffff',
      cardColor: 'rgba(15, 23, 42, 0.94)',
      enableSFX: true,
    },
  },
  {
    id: 'breaking-news',
    name: 'Breaking News Banner',
    category: 'title',
    description: 'Broadcast television breaking news lower third with pulsing LIVE pill, headline, and ticker.',
    render: renderBreakingNews,
    defaultConfig: {
      id: 'breaking-news',
      name: 'Breaking News Banner',
      category: 'title',
      description: 'Cinematic breaking news lower third banner with pulsing live badge',
      duration: 4.0,
      fps: 60,
      title: 'HISTORIC MILESTONE REACHED IN AI ACCELERATION',
      subtitle: 'Global markets surge as revolutionary open-source video engine launches worldwide.',
      badgeText: 'BREAKING NEWS',
      primaryColor: '#dc2626',
      secondaryColor: '#0284c7',
      accentColor: '#f59e0b',
      textColor: '#ffffff',
      cardColor: '#0a0a0c',
      enableSFX: true,
    },
  },
  {
    id: 'cyberpunk-hud',
    name: 'Cyberpunk HUD Callout',
    category: 'title',
    description: 'Futuristic sci-fi HUD frame with neon corner brackets, scanner line, reticle, and system telemetry.',
    render: renderCyberpunkHUD,
    defaultConfig: {
      id: 'cyberpunk-hud',
      name: 'Cyberpunk HUD Callout',
      category: 'title',
      description: 'Futuristic cybernetic HUD overlay with animated scanlines and telemetry',
      duration: 4.0,
      fps: 60,
      title: 'NEURAL CORE ACTIVE',
      subtitle: 'Sub-routine quantum encryption synced',
      badgeText: 'SECURE_NODE #84',
      primaryColor: '#00f0ff',
      secondaryColor: '#ff0055',
      accentColor: '#ffe600',
      textColor: '#ffffff',
      cardColor: 'rgba(10, 15, 29, 0.92)',
      enableSFX: true,
    },
  },
  {
    id: 'tiktok-pop',
    name: 'TikTok Follow & Heart Pop',
    category: 'social',
    description: 'TikTok creator profile card with cyan/red chromatic glow, double-tap heart burst, and follower counter.',
    render: renderTikTokPop,
    defaultConfig: {
      id: 'tiktok-pop',
      name: 'TikTok Follow & Heart Pop',
      category: 'social',
      description: 'TikTok creator banner with animated heart burst and glitch SFX',
      duration: 3.5,
      fps: 60,
      title: 'Creative Visionary',
      subtitle: '450.8K Followers',
      handle: '@creator.vision',
      avatarText: 'TT',
      primaryColor: '#FE2C55',
      secondaryColor: '#25F4EE',
      accentColor: '#ffffff',
      textColor: '#ffffff',
      cardColor: 'rgba(18, 18, 18, 0.95)',
      enableSFX: true,
    },
  },
  {
    id: 'twitter-callout',
    name: 'Twitter / X Repost Card',
    category: 'social',
    description: 'Sleek X tweet callout card with animated Retweet, Heart like pop, verified badge, and sound effects.',
    render: renderTwitterCallout,
    defaultConfig: {
      id: 'twitter-callout',
      name: 'Twitter / X Repost Card',
      category: 'social',
      description: 'Twitter / X post callout with interactive repost and like count animations',
      duration: 3.5,
      fps: 60,
      title: 'Alex Rivera',
      handle: '@alexrivera_ai',
      avatarText: 'X',
      subtitle: 'Motion graphics are 10x faster now with real-time browser rendering. Game changer! 🔥',
      primaryColor: '#1d9bf0',
      secondaryColor: '#00ba7c',
      accentColor: '#f91880',
      textColor: '#ffffff',
      cardColor: '#000000',
      enableSFX: true,
    },
  },
];
